#!/bin/sh
git diff --cached --name-status | awk '$1 == "M" { print $2}' | grep '.py' | xargs black --py36 -l 80 --check && echo '🤗 Black test passed ✅' && exit 0|| echo '🔥🔥🔥 Commit failed. ❌ You forgot to run "black --py36 -l 80 ./". Running BLACK now:' && git diff --cached --name-status | awk '$1 == "M" { print $2}' | grep '.py' | xargs black --py36 -l 80 && echo 'Done 🎄🦌🎁. Add reformatted files to your commit and try again' && exit 1




