stages:
- test
- build

tests:
  image: python:3.6
  stage: test
  services:
  - postgres:9.6.7
  variables:
    PIP_DOWNLOAD_CACHE: /cache/pip/.pip_download_cache
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

  before_script:
  - pip install -r requirements/requirements.txt
  - pip install coverage
  - pip install black --upgrade
  - python -m tests.test_app.init_db

  script:
  - black -l 80 --check --diff ./
  - coverage run --source=awokado -m unittest discover
  - coverage report -m

build:
  image: python:3.7
  stage: build
  only:
  - generate_documentation

  before_script:
    - pip install twine

  script:
  - python3 setup.py sdist bdist_wheel
  - twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing dist/* -u $PYPI_USER -p $PYPI_PASSWORD
  - git remote set-url origin https://$NPA_USER:$NPA_PASSWORD@gitlab.com/5783354/awokado.git
  - git config --global user.email $NPA_EMAIL
  - git config --global user.name $NPA_USER
  - git config --global user.password $NPA_PASSWORD
  - git tag -am 'Release v0.3b18' 0.3b18
  - git push origin 0.3b18


