[tool.black]
line-length = 80
target-version = ['py37']
include = '\.pyi?$'
skip-string-normalization = false
exclude = '''
(
  /(
    | \.git
    | \.pytest_cache
    | \.mypy_cache
    | \.venv
    | \.cache
    | data
  )/
)
'''
